# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/Add_splice.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 800)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBox_7 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_7.setMinimumSize(QtCore.QSize(115, 34))
        self.comboBox_7.setMaximumSize(QtCore.QSize(115, 34))
        self.comboBox_7.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_7)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(175, 32))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(175, 32))
        self.lineEdit_6.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout.addWidget(self.lineEdit_6)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(176, 32))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(176, 32))
        self.lineEdit_7.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.lineEdit_7.setText(_fromUtf8(""))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout.addWidget(self.lineEdit_7)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(135, 34))
        self.pushButton_2.setMaximumSize(QtCore.QSize(135, 34))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/clr_bar.png);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(400, 400))
        self.label.setMaximumSize(QtCore.QSize(400, 400))
        self.label.setStyleSheet(_fromUtf8("border-color: rgb(9, 9, 9);"))
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_2.addWidget(self.radioButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalSlider = QtGui.QSlider(self.centralwidget)
        self.verticalSlider.setMinimum(1)
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setPageStep(10)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider.setTickInterval(10)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.horizontalLayout_2.addWidget(self.verticalSlider)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout.addWidget(self.label_14)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout.addWidget(self.label_24)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(172, 42))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Main_Btn/btn_press.png);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Net Number", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "2", None))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "3", None))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "4", None))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "5", None))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "6", None))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "7", None))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "8", None))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "9", None))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "10", None))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Splice Name", None))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "No Of Points", None))
        self.pushButton_2.setText(_translate("MainWindow", "Browse Image", None))
        self.label.setText(_translate("MainWindow", "                                                                                                                                            Image                                                                                                                                                                                            ", None))
        self.radioButton_2.setText(_translate("MainWindow", "&Circle", None))
        self.radioButton.setText(_translate("MainWindow", "S&quare", None))
        self.label_5.setText(_translate("MainWindow", "100", None))
        self.label_13.setText(_translate("MainWindow", "90", None))
        self.label_14.setText(_translate("MainWindow", "80", None))
        self.label_12.setText(_translate("MainWindow", "70", None))
        self.label_9.setText(_translate("MainWindow", "60", None))
        self.label_10.setText(_translate("MainWindow", "50", None))
        self.label_11.setText(_translate("MainWindow", "40", None))
        self.label_8.setText(_translate("MainWindow", "30", None))
        self.label_7.setText(_translate("MainWindow", "20", None))
        self.label_6.setText(_translate("MainWindow", "10", None))
        self.label_24.setText(_translate("MainWindow", "1", None))
        self.pushButton_6.setText(_translate("MainWindow", "Save", None))
        self.pushButton_6.setShortcut(_translate("MainWindow", "Ctrl+S", None))

import resource_rc
