# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/configuration.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 800)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gen_label = QtGui.QLabel(self.centralwidget)
        self.gen_label.setMinimumSize(QtCore.QSize(150, 33))
        self.gen_label.setMaximumSize(QtCore.QSize(130, 33))
        self.gen_label.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Roboto [GOOG]\";"))
        self.gen_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gen_label.setObjectName(_fromUtf8("gen_label"))
        self.horizontalLayout.addWidget(self.gen_label)
        self.user_label = QtGui.QLabel(self.centralwidget)
        self.user_label.setMinimumSize(QtCore.QSize(150, 33))
        self.user_label.setMaximumSize(QtCore.QSize(130, 33))
        self.user_label.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Page_Toggle/page_unselect.png);\n"
"font: 14pt \"Roboto [GOOG]\";"))
        self.user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.user_label.setObjectName(_fromUtf8("user_label"))
        self.horizontalLayout.addWidget(self.user_label)
        self.sys_label = QtGui.QLabel(self.centralwidget)
        self.sys_label.setMinimumSize(QtCore.QSize(150, 33))
        self.sys_label.setMaximumSize(QtCore.QSize(130, 33))
        self.sys_label.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Page_Toggle/page_unselect.png);\n"
"font: 14pt \"Roboto [GOOG]\";"))
        self.sys_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_label.setObjectName(_fromUtf8("sys_label"))
        self.horizontalLayout.addWidget(self.sys_label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1440, 650))
        self.stackedWidget.setStyleSheet(_fromUtf8(""))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame = QtGui.QFrame(self.page)
        self.frame.setMinimumSize(QtCore.QSize(671, 451))
        self.frame.setMaximumSize(QtCore.QSize(671, 451))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem3)
        self.checkBox_45 = QtGui.QCheckBox(self.frame)
        self.checkBox_45.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_45.setText(_fromUtf8(""))
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.horizontalLayout_27.addWidget(self.checkBox_45)
        self.label_25 = QtGui.QLabel(self.frame)
        self.label_25.setMinimumSize(QtCore.QSize(100, 22))
        self.label_25.setMaximumSize(QtCore.QSize(163, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_27.addWidget(self.label_25)
        spacerItem4 = QtGui.QSpacerItem(207, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem5 = QtGui.QSpacerItem(77, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.lineEdit_70 = QtGui.QLineEdit(self.frame)
        self.lineEdit_70.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_70.setFrame(True)
        self.lineEdit_70.setObjectName(_fromUtf8("lineEdit_70"))
        self.horizontalLayout_17.addWidget(self.lineEdit_70)
        self.label_31 = QtGui.QLabel(self.frame)
        self.label_31.setMinimumSize(QtCore.QSize(124, 21))
        self.label_31.setMaximumSize(QtCore.QSize(124, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_17.addWidget(self.label_31)
        spacerItem6 = QtGui.QSpacerItem(292, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem8)
        self.label_33 = QtGui.QLabel(self.frame)
        self.label_33.setMinimumSize(QtCore.QSize(40, 21))
        self.label_33.setMaximumSize(QtCore.QSize(60, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_34.addWidget(self.label_33)
        spacerItem9 = QtGui.QSpacerItem(144, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem9)
        self.label_34 = QtGui.QLabel(self.frame)
        self.label_34.setMinimumSize(QtCore.QSize(60, 21))
        self.label_34.setMaximumSize(QtCore.QSize(80, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_34.addWidget(self.label_34)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        spacerItem11 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem11)
        self.label_35 = QtGui.QLabel(self.frame)
        self.label_35.setMinimumSize(QtCore.QSize(40, 21))
        self.label_35.setMaximumSize(QtCore.QSize(40, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_35.addWidget(self.label_35)
        spacerItem12 = QtGui.QSpacerItem(149, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem12)
        self.lineEdit_61 = QtGui.QLineEdit(self.frame)
        self.lineEdit_61.setMaximumSize(QtCore.QSize(120, 31))
        self.lineEdit_61.setText(_fromUtf8(""))
        self.lineEdit_61.setFrame(True)
        self.lineEdit_61.setObjectName(_fromUtf8("lineEdit_61"))
        self.horizontalLayout_35.addWidget(self.lineEdit_61)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        spacerItem14 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem14)
        self.label_38 = QtGui.QLabel(self.frame)
        self.label_38.setMinimumSize(QtCore.QSize(40, 21))
        self.label_38.setMaximumSize(QtCore.QSize(40, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_36.addWidget(self.label_38)
        spacerItem15 = QtGui.QSpacerItem(149, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem15)
        self.lineEdit_72 = QtGui.QLineEdit(self.frame)
        self.lineEdit_72.setMaximumSize(QtCore.QSize(120, 31))
        self.lineEdit_72.setFrame(True)
        self.lineEdit_72.setObjectName(_fromUtf8("lineEdit_72"))
        self.horizontalLayout_36.addWidget(self.lineEdit_72)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        spacerItem17 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem17)
        self.label_36 = QtGui.QLabel(self.frame)
        self.label_36.setMinimumSize(QtCore.QSize(40, 21))
        self.label_36.setMaximumSize(QtCore.QSize(40, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_37.addWidget(self.label_36)
        spacerItem18 = QtGui.QSpacerItem(149, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem18)
        self.lineEdit_63 = QtGui.QLineEdit(self.frame)
        self.lineEdit_63.setMaximumSize(QtCore.QSize(120, 31))
        self.lineEdit_63.setFrame(True)
        self.lineEdit_63.setObjectName(_fromUtf8("lineEdit_63"))
        self.horizontalLayout_37.addWidget(self.lineEdit_63)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_37)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem20)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lineEdit_6 = QtGui.QLineEdit(self.frame)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_7.addWidget(self.lineEdit_6, 0, 3, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem21, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 1, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.frame)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_7.addWidget(self.lineEdit_7, 1, 3, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem22, 0, 4, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.frame)
        self.pushButton_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_11.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_7.addWidget(self.pushButton_11, 1, 4, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(220, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem23, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem24)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem25)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(135, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(135, 30))
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/exp_db.png);\n"
"color: rgb(38, 177, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(130, 35))
        self.pushButton_4.setMaximumSize(QtCore.QSize(127, 35))
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Roboto [GOOG]\";"))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        spacerItem26 = QtGui.QSpacerItem(105, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem26)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem27 = QtGui.QSpacerItem(215, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem27)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout = QtGui.QGridLayout(self.page_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        spacerItem28 = QtGui.QSpacerItem(20, 70, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_15.addItem(spacerItem28)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem29)
        self.label_26 = QtGui.QLabel(self.page_2)
        self.label_26.setMinimumSize(QtCore.QSize(91, 21))
        self.label_26.setMaximumSize(QtCore.QSize(93, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_28.addWidget(self.label_26)
        self.checkBox_46 = QtGui.QCheckBox(self.page_2)
        self.checkBox_46.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_46.setText(_fromUtf8(""))
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.horizontalLayout_28.addWidget(self.checkBox_46)
        self.label_27 = QtGui.QLabel(self.page_2)
        self.label_27.setMinimumSize(QtCore.QSize(50, 21))
        self.label_27.setMaximumSize(QtCore.QSize(80, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_28.addWidget(self.label_27)
        self.checkBox_47 = QtGui.QCheckBox(self.page_2)
        self.checkBox_47.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_47.setText(_fromUtf8(""))
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.horizontalLayout_28.addWidget(self.checkBox_47)
        self.label_28 = QtGui.QLabel(self.page_2)
        self.label_28.setMinimumSize(QtCore.QSize(52, 21))
        self.label_28.setMaximumSize(QtCore.QSize(80, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_28.addWidget(self.label_28)
        self.verticalLayout_14.addLayout(self.horizontalLayout_28)
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_14.addItem(spacerItem30)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem31)
        self.label_29 = QtGui.QLabel(self.page_2)
        self.label_29.setMinimumSize(QtCore.QSize(96, 21))
        self.label_29.setMaximumSize(QtCore.QSize(96, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_29.addWidget(self.label_29)
        self.lineEdit_62 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_62.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_62.setMaxLength(2)
        self.lineEdit_62.setFrame(True)
        self.lineEdit_62.setObjectName(_fromUtf8("lineEdit_62"))
        self.horizontalLayout_29.addWidget(self.lineEdit_62)
        self.verticalLayout_14.addLayout(self.horizontalLayout_29)
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_14.addItem(spacerItem32)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem33)
        self.label_18 = QtGui.QLabel(self.page_2)
        self.label_18.setMinimumSize(QtCore.QSize(96, 21))
        self.label_18.setMaximumSize(QtCore.QSize(96, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_31.addWidget(self.label_18)
        self.lineEdit_64 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_64.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_64.setMaxLength(3)
        self.lineEdit_64.setFrame(True)
        self.lineEdit_64.setObjectName(_fromUtf8("lineEdit_64"))
        self.horizontalLayout_31.addWidget(self.lineEdit_64)
        self.verticalLayout_14.addLayout(self.horizontalLayout_31)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_14.addItem(spacerItem34)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem35)
        self.label_30 = QtGui.QLabel(self.page_2)
        self.label_30.setMinimumSize(QtCore.QSize(96, 21))
        self.label_30.setMaximumSize(QtCore.QSize(96, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_30.addWidget(self.label_30)
        self.lineEdit_69 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_69.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_69.setMaxLength(1)
        self.lineEdit_69.setFrame(True)
        self.lineEdit_69.setObjectName(_fromUtf8("lineEdit_69"))
        self.horizontalLayout_30.addWidget(self.lineEdit_69)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        spacerItem36 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_14.addItem(spacerItem36)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem37)
        self.pushButton = QtGui.QPushButton(self.page_2)
        self.pushButton.setMinimumSize(QtCore.QSize(121, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(121, 30))
        self.pushButton.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Sys_btn/sys_reboot.png);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem38)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        spacerItem39 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem39)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem40 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem40)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.checkBox_49 = QtGui.QCheckBox(self.page_2)
        self.checkBox_49.setMaximumSize(QtCore.QSize(30, 26))
        self.checkBox_49.setText(_fromUtf8(""))
        self.checkBox_49.setObjectName(_fromUtf8("checkBox_49"))
        self.horizontalLayout_20.addWidget(self.checkBox_49)
        self.label_37 = QtGui.QLabel(self.page_2)
        self.label_37.setMinimumSize(QtCore.QSize(126, 22))
        self.label_37.setMaximumSize(QtCore.QSize(163, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_20.addWidget(self.label_37)
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem41)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        spacerItem42 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem42)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.checkBox_48 = QtGui.QCheckBox(self.page_2)
        self.checkBox_48.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_48.setText(_fromUtf8(""))
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.horizontalLayout_19.addWidget(self.checkBox_48)
        self.label_32 = QtGui.QLabel(self.page_2)
        self.label_32.setMinimumSize(QtCore.QSize(100, 22))
        self.label_32.setMaximumSize(QtCore.QSize(163, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_19.addWidget(self.label_32)
        spacerItem43 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem43)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        spacerItem44 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem44)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_34 = QtGui.QCheckBox(self.page_2)
        self.checkBox_34.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_34.setText(_fromUtf8(""))
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.horizontalLayout_7.addWidget(self.checkBox_34)
        self.label_12 = QtGui.QLabel(self.page_2)
        self.label_12.setMinimumSize(QtCore.QSize(100, 22))
        self.label_12.setMaximumSize(QtCore.QSize(163, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem45)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem46 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem46)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.checkBox_30 = QtGui.QCheckBox(self.page_2)
        self.checkBox_30.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_30.setText(_fromUtf8(""))
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.horizontalLayout_12.addWidget(self.checkBox_30)
        self.label = QtGui.QLabel(self.page_2)
        self.label.setMinimumSize(QtCore.QSize(60, 22))
        self.label.setMaximumSize(QtCore.QSize(180, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_12.addWidget(self.label)
        spacerItem47 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem47)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        spacerItem48 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem48)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_35 = QtGui.QCheckBox(self.page_2)
        self.checkBox_35.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_35.setText(_fromUtf8(""))
        self.checkBox_35.setObjectName(_fromUtf8("checkBox_35"))
        self.horizontalLayout_10.addWidget(self.checkBox_35)
        self.label_40 = QtGui.QLabel(self.page_2)
        self.label_40.setMinimumSize(QtCore.QSize(80, 21))
        self.label_40.setMaximumSize(QtCore.QSize(190, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_10.addWidget(self.label_40)
        spacerItem49 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem49)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem50 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem50)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.checkBox_36 = QtGui.QCheckBox(self.page_2)
        self.checkBox_36.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_36.setText(_fromUtf8(""))
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.horizontalLayout_13.addWidget(self.checkBox_36)
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setMinimumSize(QtCore.QSize(60, 22))
        self.label_2.setMaximumSize(QtCore.QSize(180, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_13.addWidget(self.label_2)
        spacerItem51 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem51)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        spacerItem52 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem52)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.checkBox_44 = QtGui.QCheckBox(self.page_2)
        self.checkBox_44.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_44.setText(_fromUtf8(""))
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.horizontalLayout_26.addWidget(self.checkBox_44)
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setMinimumSize(QtCore.QSize(111, 22))
        self.label_4.setMaximumSize(QtCore.QSize(180, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_26.addWidget(self.label_4)
        spacerItem53 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem53)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        spacerItem54 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem54)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_15.addLayout(self.horizontalLayout_2)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem55 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_10.addItem(spacerItem55)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem56 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem56)
        self.pushButton_3 = QtGui.QPushButton(self.page_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(119, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(119, 40))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Roboto [GOOG]\";"))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        spacerItem57 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem57)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_15.addLayout(self.verticalLayout_10)
        self.gridLayout.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_5 = QtGui.QLabel(self.page_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_8.addWidget(self.label_5)
        self.textEdit = QtGui.QTextEdit(self.page_3)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_8.addWidget(self.textEdit)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem58 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem58)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit = QtGui.QLineEdit(self.page_3)
        self.lineEdit.setStyleSheet(_fromUtf8("\n"
"font: 14pt \"Roboto [GOOG]\";\n"
"color: rgb(85, 0, 255);\n"
""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.lineEdit_2 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_2.setStyleSheet(_fromUtf8("font: 14pt \"Roboto [GOOG]\";\n"
"color: rgb(85, 0, 255);\n"
""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_3.setStyleSheet(_fromUtf8("font: 14pt \"Roboto [GOOG]\";\n"
"color: rgb(85, 0, 255);\n"
""))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButton_6 = QtGui.QPushButton(self.page_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(71, 30))
        self.pushButton_6.setMaximumSize(QtCore.QSize(71, 30))
        self.pushButton_6.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/fix_color.png);"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.page_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(71, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(71, 30))
        self.pushButton_7.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/fix_color.png);"))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_9 = QtGui.QPushButton(self.page_3)
        self.pushButton_9.setMinimumSize(QtCore.QSize(71, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(71, 30))
        self.pushButton_9.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/fix_color.png);"))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout_5.addWidget(self.pushButton_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_5)
        spacerItem59 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem59)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lineEdit_4 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_4.setStyleSheet(_fromUtf8("font: 14pt \"Roboto [GOOG]\";\n"
"color: rgb(85, 0, 255);\n"
""))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_9.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_5.setStyleSheet(_fromUtf8("font: 14pt \"Roboto [GOOG]\";\n"
"color: rgb(85, 0, 255);\n"
""))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.verticalLayout_9.addWidget(self.lineEdit_5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButton_8 = QtGui.QPushButton(self.page_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(71, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(71, 30))
        self.pushButton_8.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/fix_color.png);"))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_11.addWidget(self.pushButton_8)
        self.pushButton_10 = QtGui.QPushButton(self.page_3)
        self.pushButton_10.setMinimumSize(QtCore.QSize(71, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(71, 30))
        self.pushButton_10.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/fix_color.png);"))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_11.addWidget(self.pushButton_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        spacerItem60 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem60)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_14)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem61 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem61)
        self.pushButton_5 = QtGui.QPushButton(self.page_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(119, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(119, 40))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Roboto [GOOG]\";"))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_4.addWidget(self.stackedWidget, 2, 0, 1, 1)
        spacerItem62 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem62, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.gen_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">General Config</span></p></body></html>", None))
        self.user_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">User Variables</span></p></body></html>", None))
        self.sys_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">System Config</span></p></body></html>", None))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Auto Part Load</span></p></body></html>", None))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Week Day Standard</span></p></body></html>", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Shift</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Start Time</span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">A</span></p></body></html>", None))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">B</span></p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">C</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "Pass Count", None))
        self.label_6.setText(_translate("MainWindow", "Fail Count", None))
        self.pushButton_11.setText(_translate("MainWindow", "Set", None))
        self.pushButton_2.setText(_translate("MainWindow", "Export Database", None))
        self.pushButton_4.setText(_translate("MainWindow", "SAVE", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Leak Test :</span></p></body></html>", None))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Single</span></p></body></html>", None))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Multi</span></p></body></html>", None))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Leal Test Time</span></p></body></html>", None))
        self.lineEdit_62.setPlaceholderText(_translate("MainWindow", "Sec", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">No of Cables</span></p></body></html>", None))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Leak Iteration</span></p></body></html>", None))
        self.pushButton.setText(_translate("MainWindow", "Factory Reset", None))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Report Generation</span></p><p><br/></p></body></html>", None))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Asset code</span></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Connector Visuals</span></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Tester Network</span></p></body></html>", None))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Production Display</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Tracebility</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">External Device</span></p></body></html>", None))
        self.pushButton_3.setText(_translate("MainWindow", "SAVE", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Master Barcode Data</span></p></body></html>", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Part No", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "User Var1", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "User Var2", None))
        self.pushButton_6.setText(_translate("MainWindow", "Add", None))
        self.pushButton_7.setText(_translate("MainWindow", "Add", None))
        self.pushButton_9.setText(_translate("MainWindow", "Add", None))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "User Var3", None))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "User Var4", None))
        self.pushButton_8.setText(_translate("MainWindow", "Add", None))
        self.pushButton_10.setText(_translate("MainWindow", "Add", None))
        self.pushButton_5.setText(_translate("MainWindow", "SAVE", None))

import resource_rc
