# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/Cutting_Window.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 800)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(75, 22))
        self.label_9.setMaximumSize(QtCore.QSize(75, 39))
        self.label_9.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineEdit_9 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(81, 21))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(81, 25))
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_9.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 14pt \"Roboto Condensed\";\n"
"background-color: rgbA(255, 255, 255,0);\n"
"color: rgb(255, 165, 83);"))
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_2.addWidget(self.lineEdit_9)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setMinimumSize(QtCore.QSize(81, 22))
        self.label_10.setMaximumSize(QtCore.QSize(81, 39))
        self.label_10.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.lineEdit_10 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(131, 21))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(131, 25))
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_10.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 14pt \"Roboto Condensed\";\n"
"background-color: rgbA(255, 255, 255,0);\n"
"color: rgb(255, 165, 83);"))
        self.lineEdit_10.setMaxLength(16)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_2.addWidget(self.lineEdit_10)
        spacerItem = QtGui.QSpacerItem(500, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(111, 41))
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(141, 41))
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(81, 41))
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(141, 41))
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_6.addWidget(self.label_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_6.addWidget(self.lineEdit_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(111, 41))
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_7.addWidget(self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.verticalLayout_7.addWidget(self.lineEdit_5)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(111, 41))
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.verticalLayout_8.addWidget(self.lineEdit_6)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(151, 41))
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_9.addWidget(self.label_7)
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.verticalLayout_9.addWidget(self.lineEdit_7)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(121, 41))
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
"font: 75 14pt \"Roboto [GOOG]\";"))
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_10.addWidget(self.label_8)
        self.lineEdit_8 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.verticalLayout_10.addWidget(self.lineEdit_8)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hrn_table = QtGui.QTableWidget(self.centralwidget)
        self.hrn_table.setEnabled(True)
        self.hrn_table.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.hrn_table.setStyleSheet(_fromUtf8("font: 25 16pt \"Roboto [GOOG]\";"))
        self.hrn_table.setFrameShape(QtGui.QFrame.NoFrame)
        self.hrn_table.setFrameShadow(QtGui.QFrame.Plain)
        self.hrn_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.hrn_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.hrn_table.setRowCount(2048)
        self.hrn_table.setColumnCount(128)
        self.hrn_table.setObjectName(_fromUtf8("hrn_table"))
        self.hrn_table.horizontalHeader().setVisible(False)
        self.hrn_table.horizontalHeader().setDefaultSectionSize(130)
        self.hrn_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.hrn_table)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(141, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(141, 41))
        self.pushButton.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"font: 14pt \"Roboto Condensed\";\n"
"\n"
"color: rgb(255, 255, 255);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Cable no</span></p></body></html>", None))
        self.lineEdit_9.setText(_translate("MainWindow", "1", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Part Name</span></p></body></html>", None))
        self.lineEdit_10.setText(_translate("MainWindow", "123456", None))
        self.label.setText(_translate("MainWindow", "From", None))
        self.lineEdit_2.setText(_translate("MainWindow", "1", None))
        self.label_2.setText(_translate("MainWindow", "Cavity", None))
        self.lineEdit.setText(_translate("MainWindow", "2", None))
        self.label_3.setText(_translate("MainWindow", "To", None))
        self.lineEdit_3.setText(_translate("MainWindow", "3", None))
        self.label_4.setText(_translate("MainWindow", "Cavity1", None))
        self.lineEdit_4.setText(_translate("MainWindow", "4", None))
        self.label_5.setText(_translate("MainWindow", "Name", None))
        self.lineEdit_5.setText(_translate("MainWindow", "5", None))
        self.label_6.setText(_translate("MainWindow", "Color", None))
        self.lineEdit_6.setText(_translate("MainWindow", "6", None))
        self.label_7.setText(_translate("MainWindow", "Gauge", None))
        self.lineEdit_7.setText(_translate("MainWindow", "7", None))
        self.label_8.setText(_translate("MainWindow", "Sp-Name", None))
        self.lineEdit_8.setText(_translate("MainWindow", "S-", None))
        self.pushButton.setText(_translate("MainWindow", "Import", None))

import resource_rc
