# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/fixturelib.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 800)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.tableWidget_2 = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(323, 100))
        self.tableWidget_2.setMaximumSize(QtCore.QSize(1500, 700))
        self.tableWidget_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableWidget_2.setStyleSheet(_fromUtf8("font: 25 14pt \"Roboto [GOOG]\";"))
        self.tableWidget_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget_2.setFrameShadow(QtGui.QFrame.Plain)
        self.tableWidget_2.setMidLineWidth(2)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setRowCount(2048)
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(188, 188, 188))
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180))
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(81)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget_2.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_11.addWidget(self.tableWidget_2)
        spacerItem1 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 51, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(111, 31))
        self.label_2.setMaximumSize(QtCore.QSize(111, 31))
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(157, 32))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(111, 31))
        self.label_3.setMaximumSize(QtCore.QSize(111, 31))
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(157, 32))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_10.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setMinimumSize(QtCore.QSize(60, 0))
        self.label_20.setMaximumSize(QtCore.QSize(108, 22))
        self.label_20.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_2.addWidget(self.label_20)
        self.comboBox_7 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_7.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setMinimumSize(QtCore.QSize(60, 0))
        self.label_17.setMaximumSize(QtCore.QSize(108, 22))
        self.label_17.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_3.addWidget(self.label_17)
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setMinimumSize(QtCore.QSize(55, 0))
        self.label_22.setMaximumSize(QtCore.QSize(108, 22))
        self.label_22.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_5.addWidget(self.label_22)
        self.comboBox_4 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_4.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setMinimumSize(QtCore.QSize(50, 0))
        self.label_21.setMaximumSize(QtCore.QSize(108, 22))
        self.label_21.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_6.addWidget(self.label_21)
        self.comboBox_5 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_5.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setMinimumSize(QtCore.QSize(60, 0))
        self.label_24.setMaximumSize(QtCore.QSize(108, 22))
        self.label_24.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_9.addWidget(self.label_24)
        self.comboBox_3 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_3.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setMinimumSize(QtCore.QSize(60, 0))
        self.label_23.setMaximumSize(QtCore.QSize(108, 22))
        self.label_23.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_7.addWidget(self.label_23)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(60, 0))
        self.label_19.setMaximumSize(QtCore.QSize(108, 22))
        self.label_19.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_8.addWidget(self.label_19)
        self.comboBox_6 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_6.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBox_6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(289, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(_fromUtf8("\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fixture Type", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Add Fixture Module</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Module Type :", None))
        self.label_3.setText(_translate("MainWindow", "Group No", None))
        self.label_20.setText(_translate("MainWindow", "Leak Test", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_17.setText(_translate("MainWindow", "Nav Sts", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_22.setText(_translate("MainWindow", "Conn Press", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_21.setText(_translate("MainWindow", "Sec Lock", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_24.setText(_translate("MainWindow", "Ser I/p", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_23.setText(_translate("MainWindow", "Eje Sts", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Yes", None))
        self.label_19.setText(_translate("MainWindow", "Actuation", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "No", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Yes", None))
        self.pushButton_2.setText(_translate("MainWindow", "Save", None))

import resource_rc
