# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/HA_Diagnostics.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1440, 800))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(24, 24))
        self.frame.setMaximumSize(QtCore.QSize(24, 24))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(4, 4, 16, 16))
        self.label_4.setMinimumSize(QtCore.QSize(16, 16))
        self.label_4.setMaximumSize(QtCore.QSize(16, 16))
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setStyleSheet(_fromUtf8("/*background-image:url(/home/pi/Desktop/AWHT/UI_files/final_assets/Checkbox/check.png);*/\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.frame)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(101, 21))
        self.label_5.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setMinimumSize(QtCore.QSize(24, 24))
        self.frame_6.setMaximumSize(QtCore.QSize(24, 24))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_21 = QtGui.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(4, 4, 16, 16))
        self.label_21.setMinimumSize(QtCore.QSize(16, 16))
        self.label_21.setMaximumSize(QtCore.QSize(16, 16))
        self.label_21.setStyleSheet(_fromUtf8("/*background-image:url(/home/pi/Desktop/AWHT/UI_files/final_assets/Checkbox/check.png);*/\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setMinimumSize(QtCore.QSize(0, 0))
        self.label_25.setMaximumSize(QtCore.QSize(111, 21))
        self.label_25.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_2.addWidget(self.label_25)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(160, 28))
        self.comboBox.setMaximumSize(QtCore.QSize(160, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);\n"
""))
        self.comboBox.setFrame(True)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(24, 24))
        self.frame_4.setMaximumSize(QtCore.QSize(24, 24))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_19 = QtGui.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(4, 4, 16, 16))
        self.label_19.setMinimumSize(QtCore.QSize(16, 16))
        self.label_19.setMaximumSize(QtCore.QSize(16, 16))
        self.label_19.setStyleSheet(_fromUtf8("/*background-image:url(/home/pi/Desktop/AWHT/UI_files/final_assets/Checkbox/check.png);*/\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setMaximumSize(QtCore.QSize(141, 21))
        self.label_24.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_2.addWidget(self.label_24)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(24, 24))
        self.frame_5.setMaximumSize(QtCore.QSize(24, 24))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_20 = QtGui.QLabel(self.frame_5)
        self.label_20.setGeometry(QtCore.QRect(4, 4, 16, 16))
        self.label_20.setMinimumSize(QtCore.QSize(16, 16))
        self.label_20.setStyleSheet(_fromUtf8("/*background-image:url(/home/pi/Desktop/AWHT/UI_files/final_assets/Checkbox/check.png);*/\n"
"background-color: rgba(255, 255, 255,0);"))
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.label_50 = QtGui.QLabel(self.centralwidget)
        self.label_50.setMaximumSize(QtCore.QSize(71, 21))
        self.label_50.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_2.addWidget(self.label_50)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setRowCount(1024)
        self.tableWidget.setColumnCount(1024)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Diagnostics", None))
        self.label_5.setText(_translate("MainWindow", "Check Board", None))
        self.label_25.setText(_translate("MainWindow", "Switch Status", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Show Satge Point", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "3", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "4", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "5", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "6", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "7", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "8", None))
        self.label_24.setText(_translate("MainWindow", "Show Group Point ", None))
        self.label_50.setText(_translate("MainWindow", "Self Test", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)

