# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/login.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1440, 800)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(422, 273))
        self.frame.setMaximumSize(QtCore.QSize(422, 273))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setMinimumSize(QtCore.QSize(171, 41))
        self.label_3.setMaximumSize(QtCore.QSize(171, 41))
        self.label_3.setStyleSheet(_fromUtf8("font: 25 28pt \"Roboto [GOOG]\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(200, 21))
        self.label_4.setMaximumSize(QtCore.QSize(415, 21))
        self.label_4.setStyleSheet(_fromUtf8("font: 25 14pt \"Roboto [GOOG]\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(32, 32))
        self.label_2.setMaximumSize(QtCore.QSize(32, 32))
        self.label_2.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Login_Icons/uid.png);"))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/Login_Icons/uid.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uid_lineEdit = QtGui.QLineEdit(self.frame)
        self.uid_lineEdit.setMinimumSize(QtCore.QSize(221, 21))
        self.uid_lineEdit.setMaximumSize(QtCore.QSize(221, 21))
        self.uid_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.uid_lineEdit.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 12pt \"Roboto [GOOG]\";\n"
"background-color: rgbA(255, 255, 255,0);\n"
""))
        self.uid_lineEdit.setObjectName(_fromUtf8("uid_lineEdit"))
        self.horizontalLayout.addWidget(self.uid_lineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setMinimumSize(QtCore.QSize(200, 16))
        self.line.setMaximumSize(QtCore.QSize(361, 16))
        self.line.setSizeIncrement(QtCore.QSize(0, 0))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        spacerItem2 = QtGui.QSpacerItem(86, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(32, 32))
        self.label.setMaximumSize(QtCore.QSize(32, 32))
        self.label.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Login_Icons/pw.png);"))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/Login_Icons/pw.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem3 = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pw_lineEdit = QtGui.QLineEdit(self.frame)
        self.pw_lineEdit.setMinimumSize(QtCore.QSize(221, 23))
        self.pw_lineEdit.setMaximumSize(QtCore.QSize(221, 21))
        self.pw_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pw_lineEdit.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 12pt \"Roboto [GOOG]\";\n"
"background-color: rgbA(255, 255, 255,0);"))
        self.pw_lineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.pw_lineEdit.setObjectName(_fromUtf8("pw_lineEdit"))
        self.horizontalLayout_3.addWidget(self.pw_lineEdit)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setMinimumSize(QtCore.QSize(200, 16))
        self.line_2.setMaximumSize(QtCore.QSize(361, 16))
        self.line_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_4.addWidget(self.line_2)
        spacerItem5 = QtGui.QSpacerItem(86, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"font: 14pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.reset_pw = QtGui.QLabel(self.frame)
        self.reset_pw.setMinimumSize(QtCore.QSize(150, 35))
        self.reset_pw.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.reset_pw.setFont(font)
        self.reset_pw.setStyleSheet(_fromUtf8("font: 12pt \"Roboto [GOOG]\";\n"
"color: rgb(169, 169, 169);"))
        self.reset_pw.setAlignment(QtCore.Qt.AlignCenter)
        self.reset_pw.setObjectName(_fromUtf8("reset_pw"))
        self.horizontalLayout_5.addWidget(self.reset_pw)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Welcome,</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Please enter your ID &amp; Password to Continue</span></p></body></html>", None))
        self.uid_lineEdit.setPlaceholderText(_translate("MainWindow", "Username", None))
        self.pw_lineEdit.setPlaceholderText(_translate("MainWindow", "Password", None))
        self.pushButton.setText(_translate("MainWindow", "Login", None))
        self.pushButton.setShortcut(_translate("MainWindow", "Return", None))
        self.reset_pw.setText(_translate("MainWindow", "Change Password", None))

import resource_rc
