# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/main.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HA_Editor(object):
    def setupUi(self, HA_Editor):
        HA_Editor.setObjectName(_fromUtf8("HA_Editor"))
        HA_Editor.resize(1440, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/KalpLogo.bmp")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HA_Editor.setWindowIcon(icon)
        HA_Editor.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(HA_Editor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.test = QtGui.QDockWidget(self.frame)
        self.test.setEnabled(True)
        self.test.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);\n"
""))
        self.test.setFloating(False)
        self.test.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.test.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.test.setWindowTitle(_fromUtf8(""))
        self.test.setObjectName(_fromUtf8("test"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.test.setWidget(self.dockWidgetContents)
        self.gridLayout_2.addWidget(self.test, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_16.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem1)
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_3.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setStyleSheet(_fromUtf8(""))
        self.pushButton_3.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/close-button-png-27.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 30))
        self.pushButton_3.setAutoDefault(True)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_16.addWidget(self.pushButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(281, 22))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setMinimumSize(QtCore.QSize(281, 16))
        self.label_16.setMaximumSize(QtCore.QSize(281, 16))
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(169, 169, 169);\n"
"font: 8pt \"Roboto Condensed\";"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout.addWidget(self.label_16)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(281, 22))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        HA_Editor.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(HA_Editor)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1440, 28))
        self.menuBar.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);\n"
"color: rgb(0,0,0);\n"
"border: 1px solid #00;"))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setStyleSheet(_fromUtf8("background-color: rgb(49, 49, 49);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTeaching = QtGui.QMenu(self.menuBar)
        self.menuTeaching.setStyleSheet(_fromUtf8("background-color: rgb(49, 49, 49);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.menuTeaching.setObjectName(_fromUtf8("menuTeaching"))
        self.menu_Config = QtGui.QMenu(self.menuBar)
        self.menu_Config.setStyleSheet(_fromUtf8("background-color: rgb(49, 49, 49);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.menu_Config.setObjectName(_fromUtf8("menu_Config"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setAutoFillBackground(False)
        self.menuHelp.setStyleSheet(_fromUtf8("background-color: rgb(49, 49, 49);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuLibraries = QtGui.QMenu(self.menuBar)
        self.menuLibraries.setStyleSheet(_fromUtf8("background-color: rgb(49, 49, 49);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.menuLibraries.setObjectName(_fromUtf8("menuLibraries"))
        self.menuReports = QtGui.QMenu(self.menuBar)
        self.menuReports.setStyleSheet(_fromUtf8("background-color: rgb(49, 49, 49);\n"
"color: rgb(255, 255, 255);\n"
""))
        self.menuReports.setObjectName(_fromUtf8("menuReports"))
        HA_Editor.setMenuBar(self.menuBar)
        self.actionNew_Harness = QtGui.QAction(HA_Editor)
        self.actionNew_Harness.setObjectName(_fromUtf8("actionNew_Harness"))
        self.actionOpen_Existing_Program = QtGui.QAction(HA_Editor)
        self.actionOpen_Existing_Program.setIconVisibleInMenu(True)
        self.actionOpen_Existing_Program.setProperty("shortcutVisibleInContextMenu", True)
        self.actionOpen_Existing_Program.setObjectName(_fromUtf8("actionOpen_Existing_Program"))
        self.actionSave_As = QtGui.QAction(HA_Editor)
        self.actionSave_As.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionSave_As.setIconVisibleInMenu(True)
        self.actionSave_As.setProperty("shortcutVisibleInContextMenu", True)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionClear_Barcode = QtGui.QAction(HA_Editor)
        self.actionClear_Barcode.setObjectName(_fromUtf8("actionClear_Barcode"))
        self.actionAbout_Kalptech = QtGui.QAction(HA_Editor)
        self.actionAbout_Kalptech.setIconVisibleInMenu(False)
        self.actionAbout_Kalptech.setObjectName(_fromUtf8("actionAbout_Kalptech"))
        self.actionLicence = QtGui.QAction(HA_Editor)
        self.actionLicence.setObjectName(_fromUtf8("actionLicence"))
        self.actionHA_help = QtGui.QAction(HA_Editor)
        self.actionHA_help.setObjectName(_fromUtf8("actionHA_help"))
        self.actionTester_Network = QtGui.QAction(HA_Editor)
        self.actionTester_Network.setObjectName(_fromUtf8("actionTester_Network"))
        self.actionTracebility = QtGui.QAction(HA_Editor)
        self.actionTracebility.setObjectName(_fromUtf8("actionTracebility"))
        self.actionProduction_Display = QtGui.QAction(HA_Editor)
        self.actionProduction_Display.setObjectName(_fromUtf8("actionProduction_Display"))
        self.actionGeneral_Configuration = QtGui.QAction(HA_Editor)
        self.actionGeneral_Configuration.setObjectName(_fromUtf8("actionGeneral_Configuration"))
        self.actionSystem_Configuration = QtGui.QAction(HA_Editor)
        self.actionSystem_Configuration.setObjectName(_fromUtf8("actionSystem_Configuration"))
        self.actionManage_Group = QtGui.QAction(HA_Editor)
        self.actionManage_Group.setObjectName(_fromUtf8("actionManage_Group"))
        self.actionGeneral_Setting = QtGui.QAction(HA_Editor)
        self.actionGeneral_Setting.setObjectName(_fromUtf8("actionGeneral_Setting"))
        self.actionLearning_Ckt = QtGui.QAction(HA_Editor)
        self.actionLearning_Ckt.setObjectName(_fromUtf8("actionLearning_Ckt"))
        self.actionUser_Testing_Flow = QtGui.QAction(HA_Editor)
        self.actionUser_Testing_Flow.setObjectName(_fromUtf8("actionUser_Testing_Flow"))
        self.actionClear_Baecode = QtGui.QAction(HA_Editor)
        self.actionClear_Baecode.setObjectName(_fromUtf8("actionClear_Baecode"))
        self.actionExit = QtGui.QAction(HA_Editor)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setProperty("shortcutVisibleInContextMenu", True)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSplice_Visualization = QtGui.QAction(HA_Editor)
        self.actionSplice_Visualization.setObjectName(_fromUtf8("actionSplice_Visualization"))
        self.actionSelect_Harness = QtGui.QAction(HA_Editor)
        self.actionSelect_Harness.setObjectName(_fromUtf8("actionSelect_Harness"))
        self.actionConnector_Library = QtGui.QAction(HA_Editor)
        self.actionConnector_Library.setObjectName(_fromUtf8("actionConnector_Library"))
        self.actionColor_Library = QtGui.QAction(HA_Editor)
        self.actionColor_Library.setObjectName(_fromUtf8("actionColor_Library"))
        self.actionFixture_Library = QtGui.QAction(HA_Editor)
        self.actionFixture_Library.setObjectName(_fromUtf8("actionFixture_Library"))
        self.actionGroup_Library = QtGui.QAction(HA_Editor)
        self.actionGroup_Library.setObjectName(_fromUtf8("actionGroup_Library"))
        self.actionDevice_Details = QtGui.QAction(HA_Editor)
        self.actionDevice_Details.setObjectName(_fromUtf8("actionDevice_Details"))
        self.actionLabel_and_Brcode_Data = QtGui.QAction(HA_Editor)
        self.actionLabel_and_Brcode_Data.setObjectName(_fromUtf8("actionLabel_and_Brcode_Data"))
        self.actionProduction_Logs = QtGui.QAction(HA_Editor)
        self.actionProduction_Logs.setObjectName(_fromUtf8("actionProduction_Logs"))
        self.actionTest_Reports = QtGui.QAction(HA_Editor)
        self.actionTest_Reports.setObjectName(_fromUtf8("actionTest_Reports"))
        self.actionLogout = QtGui.QAction(HA_Editor)
        self.actionLogout.setObjectName(_fromUtf8("actionLogout"))
        self.actionComponent_Testing = QtGui.QAction(HA_Editor)
        self.actionComponent_Testing.setObjectName(_fromUtf8("actionComponent_Testing"))
        self.actionAdd_Splice = QtGui.QAction(HA_Editor)
        self.actionAdd_Splice.setObjectName(_fromUtf8("actionAdd_Splice"))
        self.actionDignostics = QtGui.QAction(HA_Editor)
        self.actionDignostics.setObjectName(_fromUtf8("actionDignostics"))
        self.actionGroup_Data = QtGui.QAction(HA_Editor)
        self.actionGroup_Data.setObjectName(_fromUtf8("actionGroup_Data"))
        self.menuFile.addAction(self.actionNew_Harness)
        self.menuFile.addAction(self.actionSelect_Harness)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDignostics)
        self.menuFile.addAction(self.actionSplice_Visualization)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLogout)
        self.menuFile.addAction(self.actionExit)
        self.menuTeaching.addAction(self.actionGeneral_Setting)
        self.menuTeaching.addAction(self.actionLearning_Ckt)
        self.menuTeaching.addSeparator()
        self.menuTeaching.addAction(self.actionComponent_Testing)
        self.menuTeaching.addAction(self.actionUser_Testing_Flow)
        self.menuTeaching.addSeparator()
        self.menuTeaching.addAction(self.actionGroup_Data)
        self.menuTeaching.addAction(self.actionLabel_and_Brcode_Data)
        self.menu_Config.addAction(self.actionGeneral_Configuration)
        self.menu_Config.addAction(self.actionSystem_Configuration)
        self.menuHelp.addAction(self.actionAbout_Kalptech)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionLicence)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDevice_Details)
        self.menuHelp.addAction(self.actionHA_help)
        self.menuLibraries.addAction(self.actionConnector_Library)
        self.menuLibraries.addAction(self.actionColor_Library)
        self.menuLibraries.addAction(self.actionFixture_Library)
        self.menuLibraries.addAction(self.actionGroup_Library)
        self.menuLibraries.addAction(self.actionAdd_Splice)
        self.menuReports.addAction(self.actionProduction_Logs)
        self.menuReports.addAction(self.actionTest_Reports)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTeaching.menuAction())
        self.menuBar.addAction(self.menuLibraries.menuAction())
        self.menuBar.addAction(self.menu_Config.menuAction())
        self.menuBar.addAction(self.menuReports.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(HA_Editor)
        QtCore.QMetaObject.connectSlotsByName(HA_Editor)

    def retranslateUi(self, HA_Editor):
        HA_Editor.setWindowTitle(_translate("HA_Editor", "Harness Editor", None))
        self.pushButton_3.setToolTip(_translate("HA_Editor", "Close window", None))
        self.label.setText(_translate("HA_Editor", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">sales@kalptechsolutions.com</span></p></body></html>", None))
        self.label_16.setText(_translate("HA_Editor", "Copyright © 2019 Kalptech solutions Pvt Ltd. All rights reserved.", None))
        self.label_2.setText(_translate("HA_Editor", "<html><head/><body><p><a href=\"http://www.kalptechsolutions.com/\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">www.kalptechsolutions.com</span></a></p></body></html>", None))
        self.menuFile.setTitle(_translate("HA_Editor", "&File", None))
        self.menuTeaching.setTitle(_translate("HA_Editor", "&Teaching", None))
        self.menu_Config.setTitle(_translate("HA_Editor", "&Config", None))
        self.menuHelp.setTitle(_translate("HA_Editor", "He&lp", None))
        self.menuLibraries.setTitle(_translate("HA_Editor", "L&ibraries", None))
        self.menuReports.setTitle(_translate("HA_Editor", "&Reports", None))
        self.actionNew_Harness.setText(_translate("HA_Editor", "&New Harness", None))
        self.actionOpen_Existing_Program.setText(_translate("HA_Editor", "&Open Existing Program", None))
        self.actionOpen_Existing_Program.setShortcut(_translate("HA_Editor", "Ctrl+O", None))
        self.actionSave_As.setText(_translate("HA_Editor", "&Save As/Copy", None))
        self.actionSave_As.setShortcut(_translate("HA_Editor", "Ctrl+Shift+S", None))
        self.actionClear_Barcode.setText(_translate("HA_Editor", "&Clear Barcode", None))
        self.actionAbout_Kalptech.setText(_translate("HA_Editor", "&About Kalptech", None))
        self.actionLicence.setText(_translate("HA_Editor", "&Licence And Legality", None))
        self.actionHA_help.setText(_translate("HA_Editor", "&Product help", None))
        self.actionTester_Network.setText(_translate("HA_Editor", "&Tester Network", None))
        self.actionTracebility.setText(_translate("HA_Editor", "T&racebility", None))
        self.actionProduction_Display.setText(_translate("HA_Editor", "&Production Display", None))
        self.actionGeneral_Configuration.setText(_translate("HA_Editor", "&General Configuration", None))
        self.actionSystem_Configuration.setText(_translate("HA_Editor", "&System Configuration", None))
        self.actionManage_Group.setText(_translate("HA_Editor", "&Manage Group", None))
        self.actionGeneral_Setting.setText(_translate("HA_Editor", "&General Setting", None))
        self.actionLearning_Ckt.setText(_translate("HA_Editor", "&Learn Circuits", None))
        self.actionUser_Testing_Flow.setText(_translate("HA_Editor", "&User Testing Flow", None))
        self.actionClear_Baecode.setText(_translate("HA_Editor", "Exit", None))
        self.actionExit.setText(_translate("HA_Editor", "&Exit", None))
        self.actionExit.setShortcut(_translate("HA_Editor", "Ctrl+Q", None))
        self.actionSplice_Visualization.setText(_translate("HA_Editor", "Splice &Visualization", None))
        self.actionSelect_Harness.setText(_translate("HA_Editor", "Select &Location", None))
        self.actionConnector_Library.setText(_translate("HA_Editor", "&Connector Library", None))
        self.actionColor_Library.setText(_translate("HA_Editor", "Color &Library", None))
        self.actionFixture_Library.setText(_translate("HA_Editor", "&Module Library", None))
        self.actionGroup_Library.setText(_translate("HA_Editor", "&Group Library", None))
        self.actionDevice_Details.setText(_translate("HA_Editor", "&Device Details", None))
        self.actionLabel_and_Brcode_Data.setText(_translate("HA_Editor", "Label and Brcode Data", None))
        self.actionProduction_Logs.setText(_translate("HA_Editor", "Production Logs", None))
        self.actionTest_Reports.setText(_translate("HA_Editor", "Test Reports", None))
        self.actionLogout.setText(_translate("HA_Editor", "Logout", None))
        self.actionComponent_Testing.setText(_translate("HA_Editor", "Component Testing", None))
        self.actionAdd_Splice.setText(_translate("HA_Editor", "Add Splice", None))
        self.actionDignostics.setText(_translate("HA_Editor", "Dignostics", None))
        self.actionGroup_Data.setText(_translate("HA_Editor", "Group Data", None))

import resource_rc
