# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/new_Mdi.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1440, 800))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setMaximumSize(QtCore.QSize(206, 22))
        self.label_18.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_8.addWidget(self.label_18)
        self.msg_line = QtGui.QLineEdit(self.centralwidget)
        self.msg_line.setEnabled(True)
        self.msg_line.setMinimumSize(QtCore.QSize(481, 35))
        self.msg_line.setMaximumSize(QtCore.QSize(650, 35))
        self.msg_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.msg_line.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 16pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 119, 143);"))
        self.msg_line.setText(_fromUtf8(""))
        self.msg_line.setObjectName(_fromUtf8("msg_line"))
        self.verticalLayout_8.addWidget(self.msg_line)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_2.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_2.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Slide_Page/bck_normal.png);"))
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_3.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Slide_Page/nxt_normal.png);"))
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(35, 32))
        self.pushButton_5.setMaximumSize(QtCore.QSize(35, 32))
        self.pushButton_5.setStyleSheet(_fromUtf8(""))
        self.pushButton_5.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 30))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(400, 250))
        self.label.setMaximumSize(QtCore.QSize(800, 500))
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(195, 195, 195);"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(681, 500))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setEnabled(True)
        self.label_8.setMinimumSize(QtCore.QSize(120, 30))
        self.label_8.setMaximumSize(QtCore.QSize(120, 30))
        self.label_8.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem1 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setMinimumSize(QtCore.QSize(50, 30))
        self.label_20.setMaximumSize(QtCore.QSize(50, 30))
        self.label_20.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_5.addWidget(self.label_20)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setEnabled(True)
        self.label_9.setMinimumSize(QtCore.QSize(100, 30))
        self.label_9.setMaximumSize(QtCore.QSize(100, 30))
        self.label_9.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(250, 30))
        self.label_19.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_5.addWidget(self.label_19)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setMaximumSize(QtCore.QSize(124, 20))
        self.label_17.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        self.barcode_scan_line = QtGui.QLineEdit(self.frame)
        self.barcode_scan_line.setMinimumSize(QtCore.QSize(0, 0))
        self.barcode_scan_line.setMaximumSize(QtCore.QSize(497, 31))
        self.barcode_scan_line.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.barcode_scan_line.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.barcode_scan_line.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"color: rgb(255, 119, 143);\n"
"font: 18pt \"Roboto [GOOG]\";"))
        self.barcode_scan_line.setText(_fromUtf8(""))
        self.barcode_scan_line.setObjectName(_fromUtf8("barcode_scan_line"))
        self.verticalLayout_7.addWidget(self.barcode_scan_line)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setEnabled(True)
        self.label_7.setMaximumSize(QtCore.QSize(101, 20))
        self.label_7.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.pass_cnt_line = QtGui.QLineEdit(self.frame)
        self.pass_cnt_line.setEnabled(True)
        self.pass_cnt_line.setMinimumSize(QtCore.QSize(111, 21))
        self.pass_cnt_line.setMaximumSize(QtCore.QSize(111, 30))
        self.pass_cnt_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pass_cnt_line.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 16pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 165, 83);"))
        self.pass_cnt_line.setMaxLength(6)
        self.pass_cnt_line.setObjectName(_fromUtf8("pass_cnt_line"))
        self.verticalLayout_3.addWidget(self.pass_cnt_line)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setEnabled(True)
        self.label_6.setMaximumSize(QtCore.QSize(91, 20))
        self.label_6.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.fail_cnt_line = QtGui.QLineEdit(self.frame)
        self.fail_cnt_line.setEnabled(True)
        self.fail_cnt_line.setMinimumSize(QtCore.QSize(111, 21))
        self.fail_cnt_line.setMaximumSize(QtCore.QSize(111, 30))
        self.fail_cnt_line.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fail_cnt_line.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 16pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 165, 83);"))
        self.fail_cnt_line.setMaxLength(6)
        self.fail_cnt_line.setObjectName(_fromUtf8("fail_cnt_line"))
        self.verticalLayout_4.addWidget(self.fail_cnt_line)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setEnabled(True)
        self.label_10.setMaximumSize(QtCore.QSize(100, 20))
        self.label_10.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";\n"
""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.fo_qty = QtGui.QLineEdit(self.frame)
        self.fo_qty.setEnabled(True)
        self.fo_qty.setMinimumSize(QtCore.QSize(111, 21))
        self.fo_qty.setMaximumSize(QtCore.QSize(111, 30))
        self.fo_qty.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fo_qty.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 16pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 165, 83);"))
        self.fo_qty.setMaxLength(6)
        self.fo_qty.setObjectName(_fromUtf8("fo_qty"))
        self.verticalLayout.addWidget(self.fo_qty)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setMinimumSize(QtCore.QSize(124, 35))
        self.label_21.setMaximumSize(QtCore.QSize(124, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Toggle_fun/pro_icon.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setIndent(9)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_8.addWidget(self.label_21)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.pushButton = QtGui.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(137, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(115, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(True)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/normal.png);\n"
"font: 14pt \"Roboto [GOOG]\";\n"
"\n"
""))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_8.addWidget(self.pushButton)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.Enter_btn = QtGui.QPushButton(self.frame)
        self.Enter_btn.setMinimumSize(QtCore.QSize(110, 35))
        self.Enter_btn.setMaximumSize(QtCore.QSize(124, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Enter_btn.setFont(font)
        self.Enter_btn.setMouseTracking(False)
        self.Enter_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Enter_btn.setStyleSheet(_fromUtf8("\n"
"border-image: url(:/images/final_assets/Secondary_btn/normal.png);\n"
"font: 16pt \"Roboto [GOOG]\";\n"
"color: rgb(38,177,255);\n"
""))
        self.Enter_btn.setAutoDefault(False)
        self.Enter_btn.setDefault(False)
        self.Enter_btn.setFlat(True)
        self.Enter_btn.setObjectName(_fromUtf8("Enter_btn"))
        self.horizontalLayout_8.addWidget(self.Enter_btn)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setMinimumSize(QtCore.QSize(0, 200))
        self.mdiArea.setMaximumSize(QtCore.QSize(1440, 300))
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 238))
        brush.setStyle(QtCore.Qt.Dense7Pattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setActivationOrder(QtGui.QMdiArea.CreationOrder)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.horizontalLayout_9.addWidget(self.mdiArea)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem13)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_18.setText(_translate("MainWindow", "Operations & Messages", None))
        self.msg_line.setPlaceholderText(_translate("MainWindow", "Operational messages", None))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Previous Error Message", None))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Next Error Message", None))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Abort ", None))
        self.label.setText(_translate("MainWindow", "Image", None))
        self.label_8.setText(_translate("MainWindow", "Location No.  :", None))
        self.label_9.setText(_translate("MainWindow", "Part Name  :", None))
        self.label_17.setText(_translate("MainWindow", "Barcode Data", None))
        self.barcode_scan_line.setPlaceholderText(_translate("MainWindow", "Bar scan data", None))
        self.label_7.setText(_translate("MainWindow", "Pass Count", None))
        self.pass_cnt_line.setPlaceholderText(_translate("MainWindow", "999999", None))
        self.label_6.setText(_translate("MainWindow", "Fail Count", None))
        self.fail_cnt_line.setPlaceholderText(_translate("MainWindow", "999999", None))
        self.label_10.setText(_translate("MainWindow", "FO Quantity", None))
        self.fo_qty.setPlaceholderText(_translate("MainWindow", "999999", None))
        self.label_21.setToolTip(_translate("MainWindow", "Click to Sample Mode", None))
        self.label_21.setText(_translate("MainWindow", "Production", None))
        self.pushButton.setText(_translate("MainWindow", "Diagnostics", None))
        self.Enter_btn.setToolTip(_translate("MainWindow", "Testing Start", None))
        self.Enter_btn.setText(_translate("MainWindow", "START", None))

import resource_rc
