# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/Prod_Logs.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 800)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(350, 100))
        self.tableWidget.setMaximumSize(QtCore.QSize(1500, 586))
        self.tableWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableWidget.setStyleSheet(_fromUtf8("font: 25 14pt \"Roboto [GOOG]\";"))
        self.tableWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.tableWidget.setMidLineWidth(2)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(2048)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(188, 188, 188))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(195, 195, 195))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(195, 195, 195))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(82)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setMinimumSize(QtCore.QSize(40, 21))
        self.label_18.setMaximumSize(QtCore.QSize(40, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout.addWidget(self.label_18)
        self.lineEdit_10 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(41, 35))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(41, 35))
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_10.setStyleSheet(_fromUtf8("color: rgb(38, 177, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_10.setMaxLength(2)
        self.lineEdit_10.setFrame(False)
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout.addWidget(self.lineEdit_10)
        self.lineEdit_11 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(41, 35))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(41, 35))
        self.lineEdit_11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_11.setStyleSheet(_fromUtf8("color: rgb(38, 177, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_11.setMaxLength(2)
        self.lineEdit_11.setFrame(False)
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout.addWidget(self.lineEdit_11)
        self.lineEdit_19 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(61, 35))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(61, 35))
        self.lineEdit_19.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_19.setStyleSheet(_fromUtf8("color: rgb(38, 177, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_19.setMaxLength(4)
        self.lineEdit_19.setFrame(False)
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.horizontalLayout.addWidget(self.lineEdit_19)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(25, 21))
        self.label_19.setMaximumSize(QtCore.QSize(25, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout.addWidget(self.label_19)
        self.lineEdit_24 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_24.setMinimumSize(QtCore.QSize(41, 35))
        self.lineEdit_24.setMaximumSize(QtCore.QSize(41, 35))
        self.lineEdit_24.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_24.setStyleSheet(_fromUtf8("color: rgb(38, 177, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_24.setMaxLength(2)
        self.lineEdit_24.setFrame(False)
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.horizontalLayout.addWidget(self.lineEdit_24)
        self.lineEdit_26 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_26.setMinimumSize(QtCore.QSize(41, 35))
        self.lineEdit_26.setMaximumSize(QtCore.QSize(41, 35))
        self.lineEdit_26.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_26.setStyleSheet(_fromUtf8("color: rgb(38, 177, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_26.setMaxLength(2)
        self.lineEdit_26.setFrame(False)
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.horizontalLayout.addWidget(self.lineEdit_26)
        self.lineEdit_25 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_25.setMinimumSize(QtCore.QSize(61, 35))
        self.lineEdit_25.setMaximumSize(QtCore.QSize(61, 35))
        self.lineEdit_25.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_25.setStyleSheet(_fromUtf8("color: rgb(38, 177, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_25.setMaxLength(4)
        self.lineEdit_25.setFrame(False)
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.horizontalLayout.addWidget(self.lineEdit_25)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/exp_db.png);"))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/exp_db.png);"))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date_Time", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Location_No", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Part Name", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Event", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">From</span></p></body></html>", None))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "01", None))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "01", None))
        self.lineEdit_19.setPlaceholderText(_translate("MainWindow", "2020", None))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">To</span></p></body></html>", None))
        self.lineEdit_24.setPlaceholderText(_translate("MainWindow", "01", None))
        self.lineEdit_26.setPlaceholderText(_translate("MainWindow", "10", None))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "2020", None))
        self.pushButton.setText(_translate("MainWindow", "Fetch Report", None))
        self.pushButton_2.setText(_translate("MainWindow", "Export", None))

import resource_rc
