# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/HA_Editor/UI_files/reset_pw.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(403, 333)
        MainWindow.setMaximumSize(QtCore.QSize(1440, 800))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(361, 22))
        self.label_4.setMaximumSize(QtCore.QSize(361, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("font: 25 14pt \"Roboto [GOOG]\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(32, 29))
        self.label.setMaximumSize(QtCore.QSize(32, 24))
        self.label.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Login_Icons/pw.png);"))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/Login_Icons/pw.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.newpw_lineedit_2 = QtGui.QLineEdit(self.centralwidget)
        self.newpw_lineedit_2.setMinimumSize(QtCore.QSize(113, 21))
        self.newpw_lineedit_2.setMaximumSize(QtCore.QSize(113, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.newpw_lineedit_2.setFont(font)
        self.newpw_lineedit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.newpw_lineedit_2.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 10pt \"Roboto [GOOG]\";\n"
"background-color: rgba(0, 0, 0,0);"))
        self.newpw_lineedit_2.setEchoMode(QtGui.QLineEdit.Password)
        self.newpw_lineedit_2.setObjectName(_fromUtf8("newpw_lineedit_2"))
        self.horizontalLayout_2.addWidget(self.newpw_lineedit_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(361, 16))
        self.line.setMaximumSize(QtCore.QSize(361, 16))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_10.addWidget(self.line)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(32, 32))
        self.label_2.setMaximumSize(QtCore.QSize(32, 25))
        self.label_2.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Login_Icons/new_pw.png);"))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/Login_Icons/new_pw.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem4 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.newpw_lineedit = QtGui.QLineEdit(self.centralwidget)
        self.newpw_lineedit.setMinimumSize(QtCore.QSize(113, 21))
        self.newpw_lineedit.setMaximumSize(QtCore.QSize(113, 21))
        self.newpw_lineedit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.newpw_lineedit.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 10pt \"Roboto [GOOG]\";\n"
"background-color: rgba(0, 0, 0,0);"))
        self.newpw_lineedit.setEchoMode(QtGui.QLineEdit.Password)
        self.newpw_lineedit.setObjectName(_fromUtf8("newpw_lineedit"))
        self.horizontalLayout_3.addWidget(self.newpw_lineedit)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(361, 16))
        self.line_2.setMaximumSize(QtCore.QSize(361, 16))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_11.addWidget(self.line_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(32, 32))
        self.label_3.setMaximumSize(QtCore.QSize(32, 25))
        self.label_3.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Login_Icons/new_pw.png);"))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/final_assets/Login_Icons/new_pw.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem7 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.current_lineedit = QtGui.QLineEdit(self.centralwidget)
        self.current_lineedit.setMinimumSize(QtCore.QSize(141, 21))
        self.current_lineedit.setMaximumSize(QtCore.QSize(141, 21))
        self.current_lineedit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.current_lineedit.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 10pt \"Roboto [GOOG]\";\n"
"background-color: rgba(0, 0, 0,0);"))
        self.current_lineedit.setEchoMode(QtGui.QLineEdit.Password)
        self.current_lineedit.setObjectName(_fromUtf8("current_lineedit"))
        self.horizontalLayout_4.addWidget(self.current_lineedit)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setMinimumSize(QtCore.QSize(361, 16))
        self.line_3.setMaximumSize(QtCore.QSize(361, 16))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_12.addWidget(self.line_3)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(121, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(121, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(124, 35))
        self.pushButton_2.setMaximumSize(QtCore.QSize(124, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Secondary_btn/hover.png);\n"
"color: rgb(38, 177, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Please enter &amp; confirm your new password</span></p></body></html>", None))
        self.newpw_lineedit_2.setPlaceholderText(_translate("MainWindow", "Old Password", None))
        self.newpw_lineedit.setPlaceholderText(_translate("MainWindow", "New Password", None))
        self.current_lineedit.setPlaceholderText(_translate("MainWindow", "Confirm Password", None))
        self.pushButton.setText(_translate("MainWindow", "SAVE", None))
        self.pushButton.setShortcut(_translate("MainWindow", "Return", None))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel", None))

import resource_rc
