# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Desktop/.HA_Editor/UI_files/teaching_2.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1429, 800)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(75, 22))
        self.label_8.setMaximumSize(QtCore.QSize(75, 39))
        self.label_8.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(81, 21))
        self.lineEdit.setMaximumSize(QtCore.QSize(81, 25))
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 14pt \"Roboto Condensed\";\n"
"background-color: rgbA(255, 255, 255,0);\n"
"color: rgb(255, 165, 83);"))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(81, 22))
        self.label_9.setMaximumSize(QtCore.QSize(81, 39))
        self.label_9.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(131, 21))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(131, 25))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setStyleSheet(_fromUtf8("border-radius: 1px;\n"
"font: 14pt \"Roboto Condensed\";\n"
"background-color: rgbA(255, 255, 255,0);\n"
"color: rgb(255, 165, 83);"))
        self.lineEdit_2.setMaxLength(16)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout.addWidget(self.lineEdit_2)
        spacerItem = QtGui.QSpacerItem(500, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setMinimumSize(QtCore.QSize(171, 27))
        self.checkBox.setMaximumSize(QtCore.QSize(171, 27))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.actuations = QtGui.QLabel(self.centralwidget)
        self.actuations.setMinimumSize(QtCore.QSize(150, 33))
        self.actuations.setMaximumSize(QtCore.QSize(150, 33))
        self.actuations.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Page_Toggle/page_select.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.actuations.setScaledContents(False)
        self.actuations.setAlignment(QtCore.Qt.AlignCenter)
        self.actuations.setObjectName(_fromUtf8("actuations"))
        self.horizontalLayout_2.addWidget(self.actuations)
        self.facilities = QtGui.QLabel(self.centralwidget)
        self.facilities.setMinimumSize(QtCore.QSize(151, 33))
        self.facilities.setMaximumSize(QtCore.QSize(151, 33))
        self.facilities.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Page_Toggle/page_unselect.png);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.facilities.setAlignment(QtCore.Qt.AlignCenter)
        self.facilities.setObjectName(_fromUtf8("facilities"))
        self.horizontalLayout_2.addWidget(self.facilities)
        self.facilities_2 = QtGui.QLabel(self.centralwidget)
        self.facilities_2.setMinimumSize(QtCore.QSize(181, 33))
        self.facilities_2.setMaximumSize(QtCore.QSize(163, 33))
        self.facilities_2.setStyleSheet(_fromUtf8("border-image: url(:/images/final_assets/Page_Toggle/page_unselect1.png);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.facilities_2.setAlignment(QtCore.Qt.AlignCenter)
        self.facilities_2.setObjectName(_fromUtf8("facilities_2"))
        self.horizontalLayout_2.addWidget(self.facilities_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet(_fromUtf8("/*background-image:url(/home/pi/Desktop/AWHT/UI_files/final_assets/AWH_Screens/Teaching 02.png);*/"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setMaximumSize(QtCore.QSize(59, 19))
        self.label_6.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_12.addWidget(self.label_6)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.lineEdit_3 = QtGui.QLineEdit(self.page)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(65, 31))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(65, 31))
        self.lineEdit_3.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_3.setMaxLength(2)
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_12.addWidget(self.lineEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_42 = QtGui.QLabel(self.page)
        self.label_42.setMinimumSize(QtCore.QSize(100, 19))
        self.label_42.setMaximumSize(QtCore.QSize(100, 19))
        self.label_42.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_3.addWidget(self.label_42)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.lineEdit_5 = QtGui.QLineEdit(self.page)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(65, 31))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(65, 31))
        self.lineEdit_5.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 255, 255);"))
        self.lineEdit_5.setMaxLength(2)
        self.lineEdit_5.setFrame(False)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_3.addWidget(self.lineEdit_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setMinimumSize(QtCore.QSize(55, 17))
        self.label_7.setMaximumSize(QtCore.QSize(55, 17))
        self.label_7.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_13.addWidget(self.label_7)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.lineEdit_4 = QtGui.QLineEdit(self.page)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(65, 31))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(65, 31))
        self.lineEdit_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_4.setMaxLength(2)
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_13.addWidget(self.lineEdit_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_18.addLayout(self.verticalLayout_5)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setMinimumSize(QtCore.QSize(54, 17))
        self.label_10.setMaximumSize(QtCore.QSize(54, 17))
        self.label_10.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_14.addWidget(self.label_10)
        self.frame_9 = QtGui.QFrame(self.page)
        self.frame_9.setMinimumSize(QtCore.QSize(61, 24))
        self.frame_9.setMaximumSize(QtCore.QSize(61, 24))
        self.frame_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label_4 = QtGui.QLabel(self.frame_9)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 61, 24))
        self.label_4.setMinimumSize(QtCore.QSize(61, 24))
        self.label_4.setMaximumSize(QtCore.QSize(61, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Toggle_yes_no/no.png);\n"
"font: 8pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(11)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame_9)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 25, 24))
        self.label_5.setMinimumSize(QtCore.QSize(25, 24))
        self.label_5.setMaximumSize(QtCore.QSize(25, 24))
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_11 = QtGui.QLabel(self.frame_9)
        self.label_11.setGeometry(QtCore.QRect(37, 0, 25, 24))
        self.label_11.setMinimumSize(QtCore.QSize(25, 24))
        self.label_11.setMaximumSize(QtCore.QSize(25, 24))
        self.label_11.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_14.addWidget(self.frame_9)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setMinimumSize(QtCore.QSize(50, 19))
        self.label_12.setMaximumSize(QtCore.QSize(50, 19))
        self.label_12.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_15.addWidget(self.label_12)
        self.frame_10 = QtGui.QFrame(self.page)
        self.frame_10.setMinimumSize(QtCore.QSize(61, 24))
        self.frame_10.setMaximumSize(QtCore.QSize(61, 24))
        self.frame_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.label_15 = QtGui.QLabel(self.frame_10)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 61, 24))
        self.label_15.setMinimumSize(QtCore.QSize(61, 24))
        self.label_15.setMaximumSize(QtCore.QSize(61, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Toggle_yes_no/no.png);\n"
"font: 8pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setIndent(12)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_13 = QtGui.QLabel(self.frame_10)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 25, 24))
        self.label_13.setMinimumSize(QtCore.QSize(25, 24))
        self.label_13.setMaximumSize(QtCore.QSize(25, 24))
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_16 = QtGui.QLabel(self.frame_10)
        self.label_16.setGeometry(QtCore.QRect(37, 0, 25, 24))
        self.label_16.setMinimumSize(QtCore.QSize(25, 24))
        self.label_16.setMaximumSize(QtCore.QSize(25, 24))
        self.label_16.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.frame_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem14)
        self.horizontalLayout_18.addLayout(self.verticalLayout_6)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem15)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_37 = QtGui.QLabel(self.page)
        self.label_37.setMinimumSize(QtCore.QSize(36, 18))
        self.label_37.setMaximumSize(QtCore.QSize(86, 18))
        self.label_37.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_7.addWidget(self.label_37)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem16)
        self.label_35 = QtGui.QLabel(self.page)
        self.label_35.setMinimumSize(QtCore.QSize(36, 19))
        self.label_35.setMaximumSize(QtCore.QSize(96, 19))
        self.label_35.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_7.addWidget(self.label_35)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem17)
        self.label_34 = QtGui.QLabel(self.page)
        self.label_34.setMinimumSize(QtCore.QSize(36, 20))
        self.label_34.setMaximumSize(QtCore.QSize(99, 20))
        self.label_34.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_7.addWidget(self.label_34)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem18)
        self.label_36 = QtGui.QLabel(self.page)
        self.label_36.setMinimumSize(QtCore.QSize(36, 17))
        self.label_36.setMaximumSize(QtCore.QSize(85, 17))
        self.label_36.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_7.addWidget(self.label_36)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lineEdit_15 = QtGui.QLineEdit(self.page)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_15.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_15.setMaxLength(2)
        self.lineEdit_15.setFrame(False)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.verticalLayout_8.addWidget(self.lineEdit_15)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem20)
        self.lineEdit_16 = QtGui.QLineEdit(self.page)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_16.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_16.setMaxLength(2)
        self.lineEdit_16.setFrame(False)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.verticalLayout_8.addWidget(self.lineEdit_16)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem21)
        self.lineEdit_17 = QtGui.QLineEdit(self.page)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_17.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_17.setMaxLength(2)
        self.lineEdit_17.setFrame(False)
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.verticalLayout_8.addWidget(self.lineEdit_17)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem22)
        self.lineEdit_18 = QtGui.QLineEdit(self.page)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(61, 31))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(61, 31))
        self.lineEdit_18.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_18.setMaxLength(2)
        self.lineEdit_18.setFrame(False)
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.verticalLayout_8.addWidget(self.lineEdit_18)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem23)
        self.horizontalLayout_17.addLayout(self.verticalLayout_8)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem25)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem26, 0, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.page)
        self.pushButton_4.setMinimumSize(QtCore.QSize(119, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(119, 40))
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem27, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout = QtGui.QGridLayout(self.page_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem28)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem29)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem30)
        self.label_62 = QtGui.QLabel(self.page_2)
        self.label_62.setMinimumSize(QtCore.QSize(97, 21))
        self.label_62.setMaximumSize(QtCore.QSize(97, 21))
        self.label_62.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_62.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.verticalLayout_9.addWidget(self.label_62)
        spacerItem31 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem31)
        self.label_65 = QtGui.QLabel(self.page_2)
        self.label_65.setMinimumSize(QtCore.QSize(100, 21))
        self.label_65.setMaximumSize(QtCore.QSize(100, 21))
        self.label_65.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_65.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.verticalLayout_9.addWidget(self.label_65)
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem32)
        self.label_68 = QtGui.QLabel(self.page_2)
        self.label_68.setMinimumSize(QtCore.QSize(100, 21))
        self.label_68.setMaximumSize(QtCore.QSize(140, 21))
        self.label_68.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_68.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.verticalLayout_9.addWidget(self.label_68)
        spacerItem33 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem33)
        self.label_67 = QtGui.QLabel(self.page_2)
        self.label_67.setMinimumSize(QtCore.QSize(125, 21))
        self.label_67.setMaximumSize(QtCore.QSize(125, 21))
        self.label_67.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_67.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.verticalLayout_9.addWidget(self.label_67)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem34)
        self.horizontalLayout_19.addLayout(self.verticalLayout_9)
        spacerItem35 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem35)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem36 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem36)
        self.frame_5 = QtGui.QFrame(self.page_2)
        self.frame_5.setMinimumSize(QtCore.QSize(65, 28))
        self.frame_5.setMaximumSize(QtCore.QSize(65, 28))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_26 = QtGui.QLabel(self.frame_5)
        self.label_26.setGeometry(QtCore.QRect(1, 1, 61, 24))
        self.label_26.setMinimumSize(QtCore.QSize(61, 24))
        self.label_26.setMaximumSize(QtCore.QSize(61, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Toggle_yes_no/no.png);\n"
"font: 8pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setIndent(18)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_25 = QtGui.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(0, 1, 25, 24))
        self.label_25.setMinimumSize(QtCore.QSize(25, 24))
        self.label_25.setMaximumSize(QtCore.QSize(25, 24))
        self.label_25.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_27 = QtGui.QLabel(self.frame_5)
        self.label_27.setGeometry(QtCore.QRect(39, 1, 25, 24))
        self.label_27.setMinimumSize(QtCore.QSize(25, 24))
        self.label_27.setMaximumSize(QtCore.QSize(25, 24))
        self.label_27.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_10.addWidget(self.frame_5)
        spacerItem37 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem37)
        self.frame_8 = QtGui.QFrame(self.page_2)
        self.frame_8.setMinimumSize(QtCore.QSize(65, 28))
        self.frame_8.setMaximumSize(QtCore.QSize(65, 28))
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_47 = QtGui.QLabel(self.frame_8)
        self.label_47.setGeometry(QtCore.QRect(0, 0, 61, 24))
        self.label_47.setMinimumSize(QtCore.QSize(61, 24))
        self.label_47.setMaximumSize(QtCore.QSize(61, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Toggle_yes_no/no.png);\n"
"font: 8pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setIndent(18)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_31 = QtGui.QLabel(self.frame_8)
        self.label_31.setGeometry(QtCore.QRect(0, 0, 25, 24))
        self.label_31.setMinimumSize(QtCore.QSize(25, 24))
        self.label_31.setMaximumSize(QtCore.QSize(25, 24))
        self.label_31.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.frame_8)
        self.label_32.setGeometry(QtCore.QRect(37, 0, 25, 24))
        self.label_32.setMinimumSize(QtCore.QSize(25, 24))
        self.label_32.setMaximumSize(QtCore.QSize(25, 24))
        self.label_32.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_32.setText(_fromUtf8(""))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_10.addWidget(self.frame_8)
        spacerItem38 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem38)
        self.frame_12 = QtGui.QFrame(self.page_2)
        self.frame_12.setMinimumSize(QtCore.QSize(65, 28))
        self.frame_12.setMaximumSize(QtCore.QSize(65, 28))
        self.frame_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.label_48 = QtGui.QLabel(self.frame_12)
        self.label_48.setGeometry(QtCore.QRect(1, 1, 61, 24))
        self.label_48.setMinimumSize(QtCore.QSize(61, 24))
        self.label_48.setMaximumSize(QtCore.QSize(61, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Toggle_yes_no/no.png);\n"
"font: 8pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.label_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_48.setIndent(18)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.label_49 = QtGui.QLabel(self.frame_12)
        self.label_49.setGeometry(QtCore.QRect(0, 1, 25, 24))
        self.label_49.setMinimumSize(QtCore.QSize(25, 24))
        self.label_49.setMaximumSize(QtCore.QSize(25, 24))
        self.label_49.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_49.setText(_fromUtf8(""))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.frame_12)
        self.label_50.setGeometry(QtCore.QRect(39, 1, 25, 24))
        self.label_50.setMinimumSize(QtCore.QSize(25, 24))
        self.label_50.setMaximumSize(QtCore.QSize(25, 24))
        self.label_50.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_50.setText(_fromUtf8(""))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.verticalLayout_10.addWidget(self.frame_12)
        spacerItem39 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem39)
        self.frame_6 = QtGui.QFrame(self.page_2)
        self.frame_6.setMinimumSize(QtCore.QSize(65, 28))
        self.frame_6.setMaximumSize(QtCore.QSize(65, 28))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_38 = QtGui.QLabel(self.frame_6)
        self.label_38.setGeometry(QtCore.QRect(1, 1, 61, 24))
        self.label_38.setMinimumSize(QtCore.QSize(61, 24))
        self.label_38.setMaximumSize(QtCore.QSize(61, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Toggle_yes_no/no.png);\n"
"font: 8pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_38.setIndent(18)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_29 = QtGui.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(0, 1, 25, 24))
        self.label_29.setMinimumSize(QtCore.QSize(25, 24))
        self.label_29.setMaximumSize(QtCore.QSize(25, 24))
        self.label_29.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.frame_6)
        self.label_30.setGeometry(QtCore.QRect(39, 1, 25, 24))
        self.label_30.setMinimumSize(QtCore.QSize(25, 24))
        self.label_30.setMaximumSize(QtCore.QSize(25, 24))
        self.label_30.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_10.addWidget(self.frame_6)
        spacerItem40 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem40)
        self.horizontalLayout_19.addLayout(self.verticalLayout_10)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_19)
        spacerItem41 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem41)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem42 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem42)
        self.label = QtGui.QLabel(self.page_2)
        self.label.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_11.addWidget(self.label)
        spacerItem43 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem43)
        self.label_73 = QtGui.QLabel(self.page_2)
        self.label_73.setMinimumSize(QtCore.QSize(100, 27))
        self.label_73.setMaximumSize(QtCore.QSize(120, 27))
        self.label_73.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_73.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_11.addWidget(self.label_73)
        spacerItem44 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem44)
        self.label_69 = QtGui.QLabel(self.page_2)
        self.label_69.setMinimumSize(QtCore.QSize(138, 27))
        self.label_69.setMaximumSize(QtCore.QSize(148, 27))
        self.label_69.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_69.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.verticalLayout_11.addWidget(self.label_69)
        spacerItem45 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem45)
        self.horizontalLayout_20.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        spacerItem46 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem46)
        self.comboBox = QtGui.QComboBox(self.page_2)
        self.comboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto Condensed"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.comboBox.setFont(font)
        self.comboBox.setAcceptDrops(False)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.comboBox.setEditable(False)
        self.comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_12.addWidget(self.comboBox)
        spacerItem47 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem47)
        self.frame_14 = QtGui.QFrame(self.page_2)
        self.frame_14.setMinimumSize(QtCore.QSize(65, 28))
        self.frame_14.setMaximumSize(QtCore.QSize(65, 28))
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.label_54 = QtGui.QLabel(self.frame_14)
        self.label_54.setGeometry(QtCore.QRect(1, 1, 61, 24))
        self.label_54.setMinimumSize(QtCore.QSize(61, 24))
        self.label_54.setMaximumSize(QtCore.QSize(61, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto [GOOG]"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Toggle_yes_no/no.png);\n"
"font: 8pt \"Roboto [GOOG]\";\n"
"color: rgb(255, 255, 255);"))
        self.label_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_54.setIndent(18)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.label_55 = QtGui.QLabel(self.frame_14)
        self.label_55.setGeometry(QtCore.QRect(0, 1, 25, 24))
        self.label_55.setMinimumSize(QtCore.QSize(25, 24))
        self.label_55.setMaximumSize(QtCore.QSize(25, 24))
        self.label_55.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_55.setText(_fromUtf8(""))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.frame_14)
        self.label_56.setGeometry(QtCore.QRect(39, 1, 25, 24))
        self.label_56.setMinimumSize(QtCore.QSize(25, 24))
        self.label_56.setMaximumSize(QtCore.QSize(25, 24))
        self.label_56.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255,0);\n"
"background-image: url(:/images/final_assets/Toggle_Num/Ellipse.png);"))
        self.label_56.setText(_fromUtf8(""))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.verticalLayout_12.addWidget(self.frame_14)
        spacerItem48 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem48)
        self.lineEdit_6 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(70, 32))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(70, 32))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.verticalLayout_12.addWidget(self.lineEdit_6)
        spacerItem49 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem49)
        self.horizontalLayout_20.addLayout(self.verticalLayout_12)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_20)
        spacerItem50 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem50)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        spacerItem51 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem51)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_66 = QtGui.QLabel(self.page_2)
        self.label_66.setMinimumSize(QtCore.QSize(114, 15))
        self.label_66.setMaximumSize(QtCore.QSize(114, 15))
        self.label_66.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_66.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_8.addWidget(self.label_66)
        self.frame_2 = QtGui.QFrame(self.page_2)
        self.frame_2.setMinimumSize(QtCore.QSize(26, 26))
        self.frame_2.setMaximumSize(QtCore.QSize(26, 26))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_20 = QtGui.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(0, 0, 24, 24))
        self.label_20.setMinimumSize(QtCore.QSize(24, 24))
        self.label_20.setMaximumSize(QtCore.QSize(24, 24))
        self.label_20.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Checkbox/uncheck.png);"))
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_14 = QtGui.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(4, 4, 16, 16))
        self.label_14.setMinimumSize(QtCore.QSize(16, 16))
        self.label_14.setMaximumSize(QtCore.QSize(16, 16))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_8.addWidget(self.frame_2)
        self.label_44 = QtGui.QLabel(self.page_2)
        self.label_44.setMinimumSize(QtCore.QSize(21, 16))
        self.label_44.setMaximumSize(QtCore.QSize(21, 16))
        self.label_44.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_8.addWidget(self.label_44)
        self.frame_3 = QtGui.QFrame(self.page_2)
        self.frame_3.setMinimumSize(QtCore.QSize(26, 26))
        self.frame_3.setMaximumSize(QtCore.QSize(26, 26))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_21 = QtGui.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(0, 0, 24, 24))
        self.label_21.setMinimumSize(QtCore.QSize(24, 24))
        self.label_21.setMaximumSize(QtCore.QSize(24, 24))
        self.label_21.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Checkbox/uncheck.png);"))
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_23 = QtGui.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(4, 4, 16, 16))
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.label_45 = QtGui.QLabel(self.page_2)
        self.label_45.setMinimumSize(QtCore.QSize(21, 15))
        self.label_45.setMaximumSize(QtCore.QSize(21, 15))
        self.label_45.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_8.addWidget(self.label_45)
        self.frame_4 = QtGui.QFrame(self.page_2)
        self.frame_4.setMinimumSize(QtCore.QSize(26, 26))
        self.frame_4.setMaximumSize(QtCore.QSize(26, 26))
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_22 = QtGui.QLabel(self.frame_4)
        self.label_22.setGeometry(QtCore.QRect(0, 0, 24, 24))
        self.label_22.setMinimumSize(QtCore.QSize(24, 24))
        self.label_22.setMaximumSize(QtCore.QSize(24, 24))
        self.label_22.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Checkbox/uncheck.png);"))
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_24 = QtGui.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(4, 4, 16, 16))
        self.label_24.setMinimumSize(QtCore.QSize(16, 16))
        self.label_24.setMaximumSize(QtCore.QSize(16, 16))
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.label_46 = QtGui.QLabel(self.page_2)
        self.label_46.setMinimumSize(QtCore.QSize(21, 16))
        self.label_46.setMaximumSize(QtCore.QSize(21, 16))
        self.label_46.setStyleSheet(_fromUtf8("font: 14pt \"Roboto Condensed\";"))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_8.addWidget(self.label_46)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem52 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem52)
        self.pushButton_6 = QtGui.QPushButton(self.page_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(119, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(119, 40))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        spacerItem53 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem53)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem54 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem54)
        self.pushButton_5 = QtGui.QPushButton(self.page_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(119, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(119, 40))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setStyleSheet(_fromUtf8("background-image: url(:/images/final_assets/Main_Btn/btn_normal.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Roboto [GOOG]\";"))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        spacerItem55 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem55)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem56 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem56)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableWidget = QtGui.QTableWidget(self.page_3)
        self.tableWidget.setMinimumSize(QtCore.QSize(350, 100))
        self.tableWidget.setMaximumSize(QtCore.QSize(1500, 577))
        self.tableWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableWidget.setStyleSheet(_fromUtf8("font: 25 14pt \"Roboto [GOOG]\";"))
        self.tableWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.tableWidget.setMidLineWidth(2)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(1024)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(188, 188, 188))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(180, 180, 180))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        item.setBackground(QtGui.QColor(195, 195, 195))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(102)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(84)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_5)
        spacerItem57 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem57)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_133 = QtGui.QLabel(self.page_3)
        self.label_133.setMaximumSize(QtCore.QSize(150, 35))
        self.label_133.setObjectName(_fromUtf8("label_133"))
        self.horizontalLayout_10.addWidget(self.label_133)
        self.lineEdit_11 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(64, 32))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(64, 32))
        self.lineEdit_11.setMaxLength(99999)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_10.addWidget(self.lineEdit_11)
        spacerItem58 = QtGui.QSpacerItem(39, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem58)
        self.label_134 = QtGui.QLabel(self.page_3)
        self.label_134.setMaximumSize(QtCore.QSize(150, 35))
        self.label_134.setObjectName(_fromUtf8("label_134"))
        self.horizontalLayout_10.addWidget(self.label_134)
        self.lineEdit_10 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(104, 32))
        self.lineEdit_10.setStyleSheet(_fromUtf8(""))
        self.lineEdit_10.setMaxLength(999)
        self.lineEdit_10.setFrame(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.horizontalLayout_10.addWidget(self.lineEdit_10)
        spacerItem59 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem59)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_28 = QtGui.QLabel(self.page_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_4.addWidget(self.label_28)
        spacerItem60 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem60)
        self.comboBox_22 = QtGui.QComboBox(self.page_3)
        self.comboBox_22.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_22.setMaximumSize(QtCore.QSize(140, 34))
        self.comboBox_22.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.comboBox_22.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_22.setFrame(True)
        self.comboBox_22.setObjectName(_fromUtf8("comboBox_22"))
        self.comboBox_22.addItem(_fromUtf8(""))
        self.comboBox_22.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_22)
        spacerItem61 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem61)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_139 = QtGui.QLabel(self.page_3)
        self.label_139.setMinimumSize(QtCore.QSize(106, 0))
        self.label_139.setMaximumSize(QtCore.QSize(106, 46))
        self.label_139.setObjectName(_fromUtf8("label_139"))
        self.horizontalLayout_11.addWidget(self.label_139)
        spacerItem62 = QtGui.QSpacerItem(76, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem62)
        self.label_140 = QtGui.QLabel(self.page_3)
        self.label_140.setMinimumSize(QtCore.QSize(104, 0))
        self.label_140.setMaximumSize(QtCore.QSize(104, 46))
        self.label_140.setObjectName(_fromUtf8("label_140"))
        self.horizontalLayout_11.addWidget(self.label_140)
        spacerItem63 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem63)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.checkBox_30 = QtGui.QCheckBox(self.page_3)
        self.checkBox_30.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_30.setText(_fromUtf8(""))
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.horizontalLayout_21.addWidget(self.checkBox_30)
        self.label_136 = QtGui.QLabel(self.page_3)
        self.label_136.setMinimumSize(QtCore.QSize(100, 0))
        self.label_136.setMaximumSize(QtCore.QSize(199, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_136.setFont(font)
        self.label_136.setObjectName(_fromUtf8("label_136"))
        self.horizontalLayout_21.addWidget(self.label_136)
        spacerItem64 = QtGui.QSpacerItem(82, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem64)
        self.lineEdit_61 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_61.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_61.setMaxLength(1)
        self.lineEdit_61.setFrame(True)
        self.lineEdit_61.setObjectName(_fromUtf8("lineEdit_61"))
        self.horizontalLayout_21.addWidget(self.lineEdit_61)
        spacerItem65 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem65)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.checkBox_29 = QtGui.QCheckBox(self.page_3)
        self.checkBox_29.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_29.setText(_fromUtf8(""))
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.horizontalLayout_23.addWidget(self.checkBox_29)
        self.label_135 = QtGui.QLabel(self.page_3)
        self.label_135.setMinimumSize(QtCore.QSize(100, 47))
        self.label_135.setMaximumSize(QtCore.QSize(199, 47))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_135.setFont(font)
        self.label_135.setObjectName(_fromUtf8("label_135"))
        self.horizontalLayout_23.addWidget(self.label_135)
        spacerItem66 = QtGui.QSpacerItem(82, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem66)
        self.lineEdit_58 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_58.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_58.setMaxLength(1)
        self.lineEdit_58.setFrame(True)
        self.lineEdit_58.setObjectName(_fromUtf8("lineEdit_58"))
        self.horizontalLayout_23.addWidget(self.lineEdit_58)
        spacerItem67 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem67)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.checkBox_28 = QtGui.QCheckBox(self.page_3)
        self.checkBox_28.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_28.setText(_fromUtf8(""))
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.horizontalLayout_24.addWidget(self.checkBox_28)
        self.label_137 = QtGui.QLabel(self.page_3)
        self.label_137.setMinimumSize(QtCore.QSize(100, 46))
        self.label_137.setMaximumSize(QtCore.QSize(199, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_137.setFont(font)
        self.label_137.setObjectName(_fromUtf8("label_137"))
        self.horizontalLayout_24.addWidget(self.label_137)
        spacerItem68 = QtGui.QSpacerItem(82, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem68)
        self.lineEdit_59 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_59.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_59.setMaxLength(1)
        self.lineEdit_59.setFrame(True)
        self.lineEdit_59.setObjectName(_fromUtf8("lineEdit_59"))
        self.horizontalLayout_24.addWidget(self.lineEdit_59)
        spacerItem69 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem69)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.checkBox_27 = QtGui.QCheckBox(self.page_3)
        self.checkBox_27.setMaximumSize(QtCore.QSize(21, 26))
        self.checkBox_27.setText(_fromUtf8(""))
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.horizontalLayout_25.addWidget(self.checkBox_27)
        self.label_138 = QtGui.QLabel(self.page_3)
        self.label_138.setMinimumSize(QtCore.QSize(100, 46))
        self.label_138.setMaximumSize(QtCore.QSize(199, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_138.setFont(font)
        self.label_138.setObjectName(_fromUtf8("label_138"))
        self.horizontalLayout_25.addWidget(self.label_138)
        spacerItem70 = QtGui.QSpacerItem(82, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem70)
        self.lineEdit_60 = QtGui.QLineEdit(self.page_3)
        self.lineEdit_60.setMaximumSize(QtCore.QSize(51, 31))
        self.lineEdit_60.setMaxLength(1)
        self.lineEdit_60.setFrame(True)
        self.lineEdit_60.setObjectName(_fromUtf8("lineEdit_60"))
        self.horizontalLayout_25.addWidget(self.lineEdit_60)
        spacerItem71 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem71)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_22.addLayout(self.verticalLayout)
        self.gridLayout_3.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_13.addWidget(self.stackedWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Cable no</span></p></body></html>", None))
        self.lineEdit.setText(_translate("MainWindow", "1", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Part Name</span></p></body></html>", None))
        self.lineEdit_2.setText(_translate("MainWindow", "123456", None))
        self.checkBox.setText(_translate("MainWindow", "Use Global Settings", None))
        self.actuations.setText(_translate("MainWindow", "Actuations", None))
        self.facilities.setText(_translate("MainWindow", "Facilities", None))
        self.facilities_2.setText(_translate("MainWindow", "Production settings", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Release</span></p></body></html>", None))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Fail Time</span></p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Q mark</span></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Buzzer</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "Fail", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Cutter</span></p></body></html>", None))
        self.label_15.setText(_translate("MainWindow", "No", None))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Open Point </span></p></body></html>", None))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Short Point</span></p></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Interchange </span></p></body></html>", None))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Extra Point </span></p></body></html>", None))
        self.pushButton_4.setText(_translate("MainWindow", "SAVE", None))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Label Printing</span></p></body></html>", None))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">No of Labels</span></p></body></html>", None))
        self.label_68.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Component Test</span></p></body></html>", None))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Barcode Match</span></p></body></html>", None))
        self.label_26.setText(_translate("MainWindow", "No", None))
        self.label_47.setText(_translate("MainWindow", "01", None))
        self.label_48.setText(_translate("MainWindow", "No", None))
        self.label_38.setText(_translate("MainWindow", "No", None))
        self.label.setText(_translate("MainWindow", "Testing Mode", None))
        self.label_73.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Auto Mode</span></p></body></html>", None))
        self.label_69.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">No Of Stages</span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "General ", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "All Circuit Mode ", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "All Error Mode", None))
        self.label_54.setText(_translate("MainWindow", "No", None))
        self.label_66.setText(_translate("MainWindow", "No of Barcode", None))
        self.label_44.setText(_translate("MainWindow", "01", None))
        self.label_45.setText(_translate("MainWindow", "02", None))
        self.label_46.setText(_translate("MainWindow", "03", None))
        self.pushButton_6.setText(_translate("MainWindow", "SAVE", None))
        self.pushButton_5.setText(_translate("MainWindow", "SET", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sr.No", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Asset Code", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Message", None))
        self.label_133.setText(_translate("MainWindow", "FO Quantity :", None))
        self.label_134.setText(_translate("MainWindow", "No Of Assets :", None))
        self.label_28.setText(_translate("MainWindow", "Mode:  ", None))
        self.comboBox_22.setItemText(0, _translate("MainWindow", "Sequencial", None))
        self.comboBox_22.setItemText(1, _translate("MainWindow", "Random", None))
        self.label_139.setText(_translate("MainWindow", "Sample Details", None))
        self.label_140.setText(_translate("MainWindow", "No of Samples", None))
        self.label_136.setText(_translate("MainWindow", "Open Point", None))
        self.label_135.setText(_translate("MainWindow", "Short Point", None))
        self.label_137.setText(_translate("MainWindow", "Interchange", None))
        self.label_138.setText(_translate("MainWindow", "Extra Point", None))

import resource_rc
